const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.join(__dirname, 'pdf-audiobook', 'frontend', 'app');

function walkDir(dir, callback) {
  fs.readdirSync(dir).forEach(f => {
    let dirPath = path.join(dir, f);
    let isDirectory = fs.statSync(dirPath).isDirectory();
    if (isDirectory) {
      walkDir(dirPath, callback);
    } else {
      callback(dirPath);
    }
  });
}

console.log('Starting DocuSafe PDF rebranding process...');

let filesProcessed = 0;
let filesModified = 0;

walkDir(ROOT_DIR, (filePath) => {
  if (!filePath.endsWith('.tsx') && !filePath.endsWith('.ts')) return;
  filesProcessed++;

  let content = fs.readFileSync(filePath, 'utf8');
  let originalContent = content;

  // Replace single line header
  content = content.replace(
    /<span className="font-semibold text-lg tracking-tight">PDF to Audio<\/span>/g,
    '<span className="font-semibold text-lg tracking-tight">DocuSafe PDF</span>'
  );

  // Replace multi-line header with arbitrary spacing
  content = content.replace(
    /<span className="font-semibold text-lg tracking-tight">\s*PDF to Audio\s*<\/span>/g,
    '<span className="font-semibold text-lg tracking-tight">DocuSafe PDF</span>'
  );

  // Replace any remaining instances specifically inside Header tags
  // like:
  // <span className="font-semibold text-lg tracking-tight">
  //   PDF to Audio
  // </span>
  content = content.replace(
    /<span className="font-semibold text-lg tracking-tight">[\s\r\n]*PDF to Audio[\s\r\n]*<\/span>/g,
    '<span className="font-semibold text-lg tracking-tight">DocuSafe PDF</span>'
  );

  // Replace "Generated by PDF to Audio Toolkit."
  content = content.replace(
    /Generated by PDF to Audio Toolkit\./g,
    'Generated by DocuSafe PDF.'
  );

  if (filePath.endsWith('layout.tsx')) {
    content = content.replace(
      /title: "PDF to Audio — PDF Toolkit & Converter"/g,
      'title: "DocuSafe PDF — Private PDF Toolkit & Security Auditor"'
    );
    content = content.replace(
      /Convert PDFs to audiobooks, merge, split, compress, extract text, and more. Free online PDF tools — fast, private, no upload needed./g,
      'Private PDF Toolkit. Audit security, reduce file sizes, detect signatures, inspect attachments, and execute multi-version timelines completely locally.'
    );
  }

  if (content !== originalContent) {
    fs.writeFileSync(filePath, content, 'utf8');
    console.log(`Updated: ${path.relative(ROOT_DIR, filePath)}`);
    filesModified++;
  }
});

console.log(`Rebranding complete! Processed ${filesProcessed} files, modified ${filesModified} files.`);
