export type Plan = "free" | "pro" | "business";

export type ToolAccess = {
  slug: string;
  name: string;
  category: "popular" | "security" | "print" | "business" | "ai";
  minPlan: Plan;
  taskCost: number;
  maxFiles?: number;
  processing: "client" | "server" | "hybrid" | "ai";
  output: "pdf" | "report" | "csv" | "zip" | "batch" | "txt" | "images" | "audio";
};

export const PLANS_CONFIG = {
  free: {
    dailyTasks: 5,
    monthlyTasks: null,
    maxFileSizeMb: 25,
    maxPages: 50,
    batchLimit: 1,
  },
  pro: {
    dailyTasks: null,
    monthlyTasks: 300,
    maxFileSizeMb: 250,
    maxPages: 500,
    batchLimit: 25,
  },
  business: {
    dailyTasks: null,
    monthlyTasks: 2000,
    maxFileSizeMb: 1024,
    maxPages: 2000,
    batchLimit: 250,
  },
};

export const TOOLS: ToolAccess[] = [
  // --- Popular Tools (Free) ---
  {
    slug: "merge",
    name: "Merge PDF",
    category: "popular",
    minPlan: "free",
    taskCost: 1,
    processing: "client",
    output: "pdf",
  },
  {
    slug: "split",
    name: "Split PDF",
    category: "popular",
    minPlan: "free",
    taskCost: 1,
    processing: "client",
    output: "pdf",
  },
  {
    slug: "compress",
    name: "Compress PDF",
    category: "popular",
    minPlan: "free",
    taskCost: 1,
    processing: "client",
    output: "pdf",
  },
  {
    slug: "rotate",
    name: "Rotate PDF",
    category: "popular",
    minPlan: "free",
    taskCost: 1,
    processing: "client",
    output: "pdf",
  },
  {
    slug: "pdf-to-images",
    name: "PDF to Images",
    category: "popular",
    minPlan: "free",
    taskCost: 1,
    processing: "client",
    output: "images",
  },
  {
    slug: "images-to-pdf",
    name: "Images to PDF",
    category: "popular",
    minPlan: "free",
    taskCost: 1,
    processing: "client",
    output: "pdf",
  },
  {
    slug: "extract-text",
    name: "Extract Text",
    category: "popular",
    minPlan: "free",
    taskCost: 1,
    processing: "client",
    output: "txt",
  },
  {
    slug: "form-filler",
    name: "Form Filler",
    category: "popular",
    minPlan: "free",
    taskCost: 1,
    processing: "client",
    output: "pdf",
  },
  {
    slug: "reading-time",
    name: "Reading Time Estimator",
    category: "popular",
    minPlan: "free",
    taskCost: 1,
    processing: "client",
    output: "txt",
  },
  {
    slug: "watermark",
    name: "Add Watermark",
    category: "popular",
    minPlan: "free",
    taskCost: 1,
    processing: "client",
    output: "pdf",
  },
  {
    slug: "redact",
    name: "PDF Redactor",
    category: "popular",
    minPlan: "free",
    taskCost: 1,
    processing: "client",
    output: "txt",
  },
  {
    slug: "page-labels",
    name: "Page Labels",
    category: "popular",
    minPlan: "free",
    taskCost: 1,
    processing: "client",
    output: "pdf",
  },

  // --- AI Tools (Pro / Business) ---
  {
    slug: "pdf-chat",
    name: "Chat with PDF",
    category: "ai",
    minPlan: "pro",
    taskCost: 2,
    processing: "server",
    output: "report",
  },
  {
    slug: "summarize",
    name: "Summarize PDF",
    category: "ai",
    minPlan: "pro",
    taskCost: 2,
    processing: "server",
    output: "txt",
  },
  {
    slug: "flashcards",
    name: "PDF to Flashcards",
    category: "ai",
    minPlan: "pro",
    taskCost: 3,
    processing: "server",
    output: "report",
  },
  {
    slug: "pdf-to-audio",
    name: "PDF to Audio",
    category: "ai",
    minPlan: "business",
    taskCost: 5,
    processing: "server",
    output: "audio",
  },

  // --- Security & Privacy Tools (Pro) ---
  {
    slug: "privacy-report",
    name: "Privacy Report",
    category: "security",
    minPlan: "pro",
    taskCost: 2,
    processing: "hybrid",
    output: "report",
  },
  {
    slug: "evidence-locker",
    name: "Evidence Locker",
    category: "security",
    minPlan: "pro",
    taskCost: 3,
    processing: "server",
    output: "zip",
  },
  {
    slug: "fake-redaction",
    name: "Fake Redaction",
    category: "security",
    minPlan: "pro",
    taskCost: 2,
    processing: "client",
    output: "report",
  },
  {
    slug: "attachments",
    name: "Attachment Inspector",
    category: "security",
    minPlan: "pro",
    taskCost: 1,
    processing: "client",
    output: "zip",
  },
  {
    slug: "hidden-layers",
    name: "Hidden Layers",
    category: "security",
    minPlan: "pro",
    taskCost: 1,
    processing: "client",
    output: "pdf",
  },
  {
    slug: "link-safety",
    name: "Link Safety Scanner",
    category: "security",
    minPlan: "pro",
    taskCost: 1,
    processing: "client",
    output: "report",
  },
  {
    slug: "barcode-scanner",
    name: "Barcode Scanner",
    category: "security",
    minPlan: "pro",
    taskCost: 1,
    processing: "client",
    output: "report",
  },
  {
    slug: "password-protect",
    name: "Password Protect",
    category: "security",
    minPlan: "pro",
    taskCost: 1,
    processing: "client",
    output: "pdf",
  },

  // --- Print & Scan optimization (Pro) ---
  {
    slug: "color-detector",
    name: "Color Page Detector",
    category: "print",
    minPlan: "pro",
    taskCost: 1,
    processing: "client",
    output: "report",
  },
  {
    slug: "ink-saver",
    name: "Ink Saver Optimizer",
    category: "print",
    minPlan: "pro",
    taskCost: 3,
    processing: "client",
    output: "pdf",
  },
  {
    slug: "bad-scan-detector",
    name: "Bad Scan Detector",
    category: "print",
    minPlan: "pro",
    taskCost: 2,
    processing: "client",
    output: "report",
  },
  {
    slug: "missing-pages",
    name: "Missing Pages",
    category: "print",
    minPlan: "pro",
    taskCost: 1,
    processing: "client",
    output: "report",
  },
  {
    slug: "margin-normalizer",
    name: "Margin Normalizer",
    category: "print",
    minPlan: "pro",
    taskCost: 1,
    processing: "client",
    output: "pdf",
  },
  {
    slug: "font-fixer",
    name: "Font Fixer",
    category: "print",
    minPlan: "pro",
    taskCost: 1,
    processing: "client",
    output: "pdf",
  },
  {
    slug: "weight-map",
    name: "File Weight Map",
    category: "print",
    minPlan: "pro",
    taskCost: 1,
    processing: "client",
    output: "report",
  },

  // --- Business Workflow Tools (Business) ---
  {
    slug: "timeline",
    name: "Version Diff Timeline",
    category: "business",
    minPlan: "business",
    taskCost: 5,
    processing: "client",
    output: "report",
  },
  {
    slug: "delivery-packager",
    name: "Client Delivery Packager",
    category: "business",
    minPlan: "business",
    taskCost: 5,
    processing: "client",
    output: "zip",
  },
  {
    slug: "smart-rename",
    name: "Smart Rename",
    category: "business",
    minPlan: "business",
    taskCost: 1,
    processing: "client",
    output: "batch",
  },
  {
    slug: "signature-positions",
    name: "Signature Positions",
    category: "business",
    minPlan: "business",
    taskCost: 1,
    processing: "client",
    output: "report",
  },
  {
    slug: "stamp-consistency",
    name: "Stamp Consistency",
    category: "business",
    minPlan: "business",
    taskCost: 1,
    processing: "client",
    output: "report",
  },
  {
    slug: "form-extractor",
    name: "Form Data Extractor",
    category: "business",
    minPlan: "business",
    taskCost: 1,
    processing: "client",
    output: "csv",
  },
];
